name:                atcoder
version:             0.1.0.0
github:              "githubuser/atcoder"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/atcoder#readme>

dependencies:
- base >= 4.7 && < 5
- extra
- unordered-containers
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  atcoder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder

  abc068-b:
    main:                Main.hs
    source-dirs:         abc068/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-abc088-b:
    main:                Main.hs
    source-dirs:         abc088/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-abc074-b:
    main:                Main.hs
    source-dirs:         abc074/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-abc086-b:
    main:                Main.hs
    source-dirs:         abc086/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-abc157-b:
    main:                Main.hs
    source-dirs:         abc157/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-pana2020-b:
    main:                Main.hs
    source-dirs:         pana2020/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-abc121-c:
    main:                Main.hs
    source-dirs:         abc121/c
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-abc121-b:
    main:                Main.hs
    source-dirs:         abc121/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-sb2019-b:
    main:                Main.hs
    source-dirs:         sb2019/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-cf2016-b:
    main:                Main.hs
    source-dirs:         cf2016/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -DDEBUG
    dependencies:
    - atcoder
  z-abc156-c:
    main:                Main.hs
    source-dirs:         abc156/c
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-abc139-b:
    main:                Main.hs
    source-dirs:         abc139/b
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
  z-abc395-a:
    main:                Main.hs
    source-dirs:         abc395/a
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder

tests:
  atcoder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atcoder
